### PR TITLE
Move form definition retrieval out of controller constructors for proper access checking in other contexts

### LINKED ISSUE #9: Throwing `NotFoundHttpException` in form constructor causes recursion with path-based breadcrumbs on 404/403 pages
Edit by @jensschuppe:

> There is a recursion when the constructor of the `RegisterForm` throws a `NotFoundHttpException` and the resulting 404 page includes a breadcrumb; the `PathBasedBreadcrumbBuilder` tries to resolve the title of the event registration form and causes the constructor again to issue a `NotFoundHttpException` - that's where the recursion starts.

Here tThe stacktrace. The custom PathBasedBreadcrumbBuilder is not doing anything here but calling the parent PathBasedBreadcrumbBuilder from core.

The result is a recursion.
```
RegisterForm.php:122, Drupal\civiremote_event\Form\RegisterForm->__construct()
RegisterForm.php:180, Drupal\civiremote_event\Form\RegisterForm::create()
ClassResolver.php:28, Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition()
ControllerResolver.php:116, Drupal\Core\Controller\ControllerResolver->createController()
ControllerResolver.php:68, Drupal\Core\Controller\ControllerResolver->getControllerFromDefinition()
CustomAccessCheck.php:65, Drupal\Core\Access\CustomAccessCheck->access()
AccessManager.php:160, call_user_func_array:{/var/www/html/web/core/lib/Drupal/Core/Access/AccessManager.php:160}()
AccessManager.php:160, Drupal\Core\Access\AccessManager->performCheck()
AccessManager.php:136, Drupal\Core\Access\AccessManager->check()
AccessManager.php:113, Drupal\Core\Access\AccessManager->checkRequest()
AccessAwareRouter.php:104, Drupal\Core\Routing\AccessAwareRouter->checkAccess()
AccessAwareRouter.php:89, Drupal\Core\Routing\AccessAwareRouter->matchRequest()
PathBasedBreadcrumbBuilder.php:225, Drupal\system\PathBasedBreadcrumbBuilder->getRequestForPath()
PathBasedBreadcrumbBuilder.php:171, Drupal\system\PathBasedBreadcrumbBuilder->build()
PathBasedBreadcrumbBuilder.php:21, Drupal\bwp_base\Breadcrumb\PathBasedBreadcrumbBuilder->build()
BreadcrumbManager.php:83, Drupal\Core\Breadcrumb\BreadcrumbManager->build()
…
```

### LINKED ISSUE #14: Relying on the request in the constructor of RegisterForm prevents proper access checking outside of the expected route context
**Problem/Motivation**

In the constructor of `Drupal\civiremote_event\Form\RegisterForm` the form tries to get the route parameters from the current request. This prevents proper access checking outside the context of the route, if the access checks require an initialization of the RegisterForm, which is currently the case due to the custom access callbacks on the form object. Throwing 404 or other exceptions on error there may also result in the 404 or other error leaking back to the request that tried to initialize the form object, e.g. you might see a 404 error just for rendering a link to the registration route on an overview page, if the link is access checked as part of the rendering process.

**Steps to reproduce**

Try something like this somewhere outside of the expected route request context:

```
$url = \Drupal\Core\Url::fromRoute('civiremote_event.register_form', [
  'event' => $crm_id,
  'profile' => NULL,
]);
$url->access();
```

**Proposed resolution**

As a quick fix I moved the access checks of RegisterForm and RegistrationUpdateForm to RegisterFormController and used the parameters passed in instead of the properties.

A better fix would be to refactor the form code so that relying on the request in the constructor is no longer needed.

See also #9 , which is related.

### PR DESCRIPTION
**Pull request by jensschuppe**
Fixes #14. Replaces #15.

This is a more comprehensive approach to moving form definition retrieval out of controller constructors.

The `\Drupal\civiremote_event\Controller\RegisterFormController` class now responds to all registration-related routes (register, update, cancel) and includes a combined access check that can be used reliably outside of those route contexts (e.g. when validating a URL for displaying on another page).

Also, retrieving the form definition is now done in a centralized controller method before handing things off to the respective form builders, which do not have to care for initializing things in their constructor anymore. This also prevents intermittent error messages be displayed for errors during route access checks.

@FeyP Would you be able to give this a try and leave a review?

### CODE REVIEW

**Comment by jensschuppe** [comment]
@dontub if you have time, could you have a look as well? Also, the PHPStan jobs are failing due to failing GitHub authentication …

File: modules/civiremote_event/src/Controller/RegisterFormController.php [hunk 1]
```diff
@@ -16,32 +16,114 @@
...
+use Drupal\civiremote_event\CiviMRF;
 use Drupal\civiremote_event\Form\RegisterForm\RegisterFormInterface;
+use Drupal\Core\Access\AccessResult;
+use Drupal\Core\Access\AccessResultAllowed;
+use Drupal\Core\Access\AccessResultNeutral;
 use Drupal\Core\Controller\ControllerBase;
+use Drupal\Core\Messenger\MessengerInterface;
+use Drupal\Core\Routing\RouteMatch;
 use stdClass;
+use \Symfony\Component\DependencyInjection\ContainerInterface;
```
Comment (dontub) [inline modules/civiremote_event/src/Controller/RegisterFormController.php]: The first `\` is superfluous.

File: modules/civiremote_event/src/Controller/RegisterFormController.php [hunk 2]
```diff
@@ -16,32 +16,114 @@
...
+     * Inject dependencies.
+     * @var CiviMRF $cmrf
+     */
+    $cmrf = $container->get('civiremote_event.cmrf');
+    return new static(
+      $cmrf
+    );
+  }
+
+  public function form(RouteMatch $route_match, string $context, stdClass $event = NULL, string $profile = NULL, stdClass $event_token = NULL) {
```
Comment (dontub) [inline modules/civiremote_event/src/Controller/RegisterFormController.php]: It could be stated in phpdoc that `$event_token` contains the event data resolved by the event token and not the event token itself. Maybe it would make sense to have a separate method for the request with event token - as of now the method signature reads like both `$event` and `$event_token` are optional, though one of them is required.

File: modules/civiremote_event/src/Controller/RegisterFormController.php [hunk 3]
```diff
@@ -16,32 +16,114 @@
...
+      $profile,
+      $context,
+      $raw_event_token,
+      $fields,
+      $messages
+    );
   }
 
-  public function title(stdClass $event = NULL, $remote_token = NULL) {
+  public function title(stdClass $event = NULL, stdClass $event_token = NULL) {
```
Comment (dontub) [inline modules/civiremote_event/src/Controller/RegisterFormController.php]: Same as above: Different method for request with token?

File: modules/civiremote_event/src/Controller/RegisterFormController.php [hunk 4]
```diff
@@ -16,32 +16,114 @@
...
+            break;
+          case 'update':
+            $profile = $event->default_update_profile;
+            break;
+          case 'cancel':
+            $profile = NULL;
+            break;
+          default:
+            throw new NotFoundHttpException(
+              $this->t('No profile found for CiviRemote event form.')
```
Comment (dontub) [inline modules/civiremote_event/src/Controller/RegisterFormController.php]: IIRC the message of a `NotFoundHttpException` is not displayed to end users, so translation wouldn't be necessary.

**Review by dontub — CHANGES_REQUESTED** [review]

**Comment by jensschuppe** [comment]
Thanks @dontub I did the changes you requested in 41052ad77df5614763976c682a41f272b3a985b4 - care to have a quick look again?

File: modules/civiremote_event/src/Controller/RegisterFormController.php [hunk 5]
```diff
@@ -16,31 +16,143 @@
...
+use Symfony\Component\DependencyInjection\ContainerInterface;
+use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
 
 class RegisterFormController extends ControllerBase {
 
-  public function form(stdClass $event = NULL, $profile = NULL) {
-    // Use default profile if not given.
-    if (!isset($profile) && isset($event)) {
-      $profile = $event->default_profile;
+  const CONTEXT_CREATE = 'create';
```
Comment (dontub) [inline modules/civiremote_event/src/Controller/RegisterFormController.php]: The constants could have a visibility.

File: modules/civiremote_event/src/Controller/RegisterFormController.php [hunk 6]
```diff
@@ -16,31 +16,143 @@
...
+   * @return static
+   */
+  public static function create(ContainerInterface $container) {
+    /**
+     * Inject dependencies.
+     * @var CiviMRF $cmrf
+     */
+    $cmrf = $container->get('civiremote_event.cmrf');
+    return new static(
+      $cmrf
```
Comment (dontub) [inline modules/civiremote_event/src/Controller/RegisterFormController.php]: This single argument argument actually doesn't need a line for itself.

**Review by dontub — CHANGES_REQUESTED** [review]

**Review by dontub — APPROVED** [review]

**Comment by jensschuppe** [comment]
This introduced a regression causing all forms for all contexts (create, update, cancel) to use the `RegisterForm` form builder class instead of the resprective subclasses. #24 fixes that.
